use_frameworks!

platform :ios, '10.0'

target 'QCLineView_Example' do
  pod 'QCLineView', :path => '../'

  target 'QCLineView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
